---
- name: Install container runtime
  hosts: all
  roles:
  - container_runtime/docker

- name: Deploy High Avaliability layer
  hosts: k8s_lb
  roles:
  - high_availability/haproxy
  - high_availability/keepalived

- name: Install Kubernetes
  hosts: all
  roles:
  - kubernetes